# Generated by Django 5.2 on 2025-07-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
