# Generated by Django 5.2 on 2025-07-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_tourpackage_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='phone',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='related_package',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='related_resort',
        ),
    ]
