# Generated by Django 5.2 on 2025-07-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_contact_rename_phone_enquiry_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='related_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.tourpackage'),
        ),
    ]
