# Generated by Django 5.2 on 2025-07-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_clientreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client_reviews/'),
        ),
    ]
