# Generated by Django 5.2 on 2025-07-19 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_clientreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='booking.category'),
        ),
    ]
