# Generated by Django 5.2 on 2025-07-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_tourpackage_days_alter_tourpackage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='parent_choice',
        ),
    ]
