# Generated by Django 5.2 on 2025-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_tourpackage_parent_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='parent_choice',
            field=models.CharField(choices=[('india', 'India Tours'), ('international', 'International Tours'), ('ayurveda', 'Ayurveda & Wellness'), ('specials', 'Eastora Specials')], default='india', help_text='Top-level classification for the tour package', max_length=20),
        ),
    ]
