# Generated by Django 5.2 on 2025-07-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_tourpackage_parent_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content_first',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='content_second',
            field=models.TextField(blank=True),
        ),
    ]
