# Generated by Django 5.2 on 2025-07-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_category_content_first_category_content_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tittle_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='tittle_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
