# Generated by Django 5.2 on 2025-08-04 05:11

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_category_tittle_first_category_tittle_second'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
