# Generated by Django 5.2 on 2025-08-04 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_tourpackage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 4, 11, 45, 20, 76396)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
