# Generated by Django 5.2 on 2025-08-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_tourpackage_created_at_tourpackage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='content_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
