# Generated by Django 5.2 on 2025-09-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_herobanner_content_alignment_alter_tourpackage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='itinerary',
            field=models.JSONField(blank=True, help_text='Day-wise itinerary', null=True),
        ),
    ]
