# Generated by Django 5.2 on 2025-10-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_tourpackage_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description for SEO. Recommended 150-160 characters.', max_length=160),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO. Defaults to category name if empty.', max_length=70),
        ),
    ]
