# Generated by Django 5.2 on 2025-10-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_category_meta_description_category_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description for SEO. Recommended 150-160 characters.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO. Defaults to package title if empty.', max_length=70, null=True),
        ),
    ]
